services:
    usersdb:
      container_name: usersdb
      ports:
        - "3306:3306"
      volumes:
        - usersdb_data:/var/lib/mysql
      environment:
        MYSQL_DATABASE: users_db
      extends:
        file: common-config.yml
        service: microservice-db-config
    recipedb:
      container_name: recipedb
      ports:
        - "3307:3306"
      volumes:
        - recipedb_data:/var/lib/mysql
      environment:
        MYSQL_DATABASE: recipe_db
      extends:
        file: common-config.yml
        service: microservice-db-config
    redis:
      image: redis:7.2
      container_name: redis-server
      restart: unless-stopped
      ports:
        - "6379:6379"
      command: [
        "redis-server",
        "--appendonly", "yes",
        "--requirepass", "Trust@@$$Banc_COOperate**#%%$$Group"
      ]
      volumes:
        - redis_data:/data

volumes:
  recipedb_data:
    driver: local
  usersdb_data:
    driver: local

  configserver:
    image: "samseyi672/configserver:1"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  recipe:
    image: "samseyi672/recipemanagement:1"
    container_name: recipemanagement-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "recipemanagement"
      SPRING_DATASOURCE_URL: "jdbc:mysql://recipedb:3306/recipe_db"
    depends_on:
      recipedb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    volumes:
      - ./docker-logs:/logs

  users:
    image: "samseyi672/usermanagment:1"
    container_name: usermanagment-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "usermanagment"
      SPRING_DATASOURCE_URL: "jdbc:mysql://usersdb:3306/users_db"
    depends_on:
      usersdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    volumes:
      - ./docker-logs:/logs

networks:
  abn_amro_bank:
    driver: "bridge"