server:
  port: 8761
spring:
  cloud:
    config:
      import-check.enabled: false
      enabled: false
  application:
    name: "eurekaserver"
#  config:
#    import: "optional:configserver:http://localhost:8071/"
eureka:
  instance:
    hostname: eurekaserver
  client:
   register-with-eureka: false
   fetch-registry: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true