services:  

    usersdb:
      container_name: usersdb
      ports:
        - "3306:3306"
      volumes:
        - usersdb_data:/var/lib/mysql
      environment:
        MYSQL_DATABASE: users_db
      extends:
        file: common-config.yml
        service: microservice-db-config

    recipedb:
      container_name: recipedb
      ports:
        - "3307:3306"
      volumes:
        - recipedb_data:/var/lib/mysql
      environment:
        MYSQL_DATABASE: recipe_db
      extends:
        file: common-config.yml
        service: microservice-db-config

    redis:
      image: redis:7.2
      container_name: redis
      restart: unless-stopped
      healthcheck:
        test: ["CMD", "redis-cli", "-a", "Trust@@$$Banc_COOperate**#%%$$Group", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5
      ports:
        - "6379:6379"
      command: [
        "redis-server",
        "--appendonly", "yes",
        "--requirepass", "Trust@@$$Banc_COOperate**#%%$$Group"
      ]
      volumes:
        - redis_data:/data

    recipe:
      image: "samseyi672/recipemanagement:1"
      container_name: recipemanagementms
      ports:
        - "8082:8082"
      environment:
        SPRING_APPLICATION_NAME: "recipemanagement"
        SPRING_REDIS_HOST: redis
        SPRING_REDIS_PORT: 6379
        SPRING_DATASOURCE_URL: "jdbc:mysql://recipedb:3306/recipe_db"
      depends_on:
        gatewayserver:
          condition: service_healthy
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
        interval: 30s
        timeout: 10s
        retries: 5
      extends:
        file: common-config.yml
        service: microservice-configserver-config
  
    gatewayserver:
      image: "samseyi672/apigateway:1"
      container_name: apigateway
      ports:
        - "8080:8080"
      depends_on:
        eurekaserver:
          condition: service_healthy
        redis:
          condition: service_healthy
        usersdb:
          condition: service_healthy
        recipedb:
          condition: service_healthy
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
        interval: 30s
        timeout: 10s
        retries: 5
      environment:
        SPRING_APPLICATION_NAME: "apigateway"
        OTEL_SERVICE_NAME: "apigateway"
        # SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"
      extends:
        file: common-config.yml
        service: microservice-eureka-config

    eurekaserver:
      image: "samseyi672/servicediscovery:1"
      container_name: eurekaserver-ms
      ports:
        - "8761:8761"
      healthcheck:
        test: "curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 1"
        interval: 20s
        timeout: 5s
        retries: 20
        start_period: 10s
      extends:
        file: common-config.yml
        service: microservice-configserver-config
      environment:
        SPRING_APPLICATION_NAME: "eurekaserver"
        SPRING_PROFILES_ACTIVE: test
        SERVER_PORT: 8761
        # OTEL_SERVICE_NAME: "eurekaserver"

    user:
      image: "samseyi672/usermanagment:1"
      container_name: user-ms
      ports:
        - "8090:8090"
      environment:
        SPRING_APPLICATION_NAME: "user"
        SPRING_REDIS_HOST: redis
        SPRING_REDIS_PORT: 6379
        SPRING_DATASOURCE_URL: "jdbc:mysql://usersdb:3306/users_db"
      depends_on:
        gatewayserver:
          condition: service_healthy
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health"]
        interval: 30s
        timeout: 10s
        retries: 5
      extends:
        file: common-config.yml
        service: microservice-configserver-config

volumes:
 recipedb_data:
   driver: local
 usersdb_data:
   driver: local
 redis_data:
   driver: local

networks:
  abn_amro_bank:
    driver: "bridge"