spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: UTC
      default-property-inclusion: non_null
  mail:
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 5000
    host: smtp.gmail.com
    port: 465
    #    port: 587
    username: samseyi672@gmail.com
    password: cxpgkwjpexctquha
    smtp:
      starttls:
        enable: true
  mvc:
    pathmatch:
      matching-strategy: path_pattern_parser
    servlet:
      multipart:
        enabled: true
        file-size-threshold: 100KB
        max-file-size: 200MB
        max-request-size: 200MB
    http:
      multipart:
        max-file-size: 200MB
        max-request-size: 200MB
    data:
      web:
        pageable:
          page-parameter: page
          size-parameter: size
          default-page-size: 6
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/recipes_db
    username: root
    password: root
    hikari:
      poolName: stevicDbPool
      maximumPoolSize: 2
      connectionTestQuery: "SELECT 1"
      idleTimeout: 30000
      maxLifetime: 180000
      validationTimeout: 5000
    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      show_sql: true
      format_sql: true
      hibernate:
        ddl-auto: update
        jdbc:
          time_zone: UTC
          open-in-view: false
        generate_statistics: false
#      sql:
#        init:
#          mode: always
    config:
      import: "optional:configserver:http://localhost:8071/"
#mail details
com:
  abnamro:
    notify:
      email_to_A: chaniya.mac.intosh@nl.abnamro.com
      email_subject_A: Registration on Recipe Manager
      email_to_C: chaniya.mac.intosh@nl.abnamro.com

resilience4j:
  ratelimiter:
    instances:
      recipeApiLimiter:
        limitForPeriod: 50
        limitRefreshPeriod: 1s
        timeoutDuration: 0
        registerHealthIndicator: true
  circuitbreaker:
    instances:
      userServiceClient:
        slidingWindowSize: 5
        failureRateThreshold: 50
        minimumNumberOfCalls: 3
        waitDurationInOpenState: 10s
        registerHealthIndicator: true
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
    instances:
      userServiceClient:
        timeoutDuration: 3s
  retry:
    instances:
      userServiceClient:
        maxAttempts: 3
        waitDuration: 2s
        retryExceptions:
          - feign.RetryableException
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 3000

management:
  metrics:
    tags:
        application:
          name: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    circuitbreakers:
      enabled: true
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
endpoints:
  shutdown:
    enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceurl:
      defaultZone: http://localhost:8761/eureka/
#for description in the eureka microservice network.
info:
  app:
    name: "usermanagement"
    description: "user management"
    version: "1.0.0"





































