spring:
  mvc:
    pathmatch:
      matching-strategy: path_pattern_parser
    servlet:
      multipart:
        enabled: true
        file-size-threshold: 100KB
        max-file-size: 200MB
        max-request-size: 200MB
    http:
      multipart:
        max-file-size: 200MB
        max-request-size: 200MB
    data:
      web:
        pageable:
          page-parameter: page
          size-parameter: size
          default-page-size: 6
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/recipes_db
    pool:
      initial-size: 1
      max-size: 2
      max-idle-time: 5m
      validation-query: SELECT 1
    username: stevic
    password: 'password'

